version: "3.5"

services:
  issue_mgr_db:
    image: postgres:12.7
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=issue_manager
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=issue_manager
    networks:
      - issue_manager_network

  issue_mgr_app:
    build: .
    expose:
      - 8000
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 issuetracker.wsgi"
    depends_on:
      - issue_mgr_db
    volumes:
      - issue_mgr_app_files:/workspace/files
    networks:
      - issue_manager_network

  issue_mgr_nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - issue_mgr_app
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - nginx_static:/var/www/html/static
      - nginx_media:/var/www/html/media
      - ./nginx-conf.d/:/etc/nginx/conf.d
    networks:
      - issue_manager_network
      - gateway_network


volumes:
  pgdata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: $HOME/artifacts/issue-manager/postgres/pgdata
  issue_mgr_app_files:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: $HOME/artifacts/issue-manager/app_files
  nginx_static:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: $HOME/artifacts/issue-manager/app_files/static
  nginx_media:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: $HOME/artifacts/issue-manager/app_files/media


networks:
  issue_manager_network:
    name: "issue_manager_network"
    driver: bridge
  gateway_network:
    external: true