version: "3.9"

services:
  db:
    image: postgres:12.7
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=issue_manager
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=issue_manager
      - POSTGRES_DATA=~/tmp/pgdata4
  web:
      build: .
      ports:
        - "8000:8000"
volumes:
  pgdata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${POSTGRES_DATA}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24