# Generated by Django 3.1.3 on 2022-02-23 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import tasks.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[("NS", "Not Started"), ("IP", "In Progress"), ("D", "Done")],
                        default=tasks.enums.TaskStatusEnum["NOT_STARTED"],
                        help_text="* (NS, Not Started)\n* (IP, In Progress)\n* (D, Done)",
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
