# Generated by Django 3.1.3 on 2022-02-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201206_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Done')], default=1),
        ),
    ]
