# Generated by Django 3.1.3 on 2022-02-23 20:37

from django.db import migrations, models
import tasks.enums


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_auto_20220220_2112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("NS", "Not Started"), ("IP", "In Progress"), ("D", "Done")],
                default=tasks.enums.TaskStatusEnum["NOT_STARTED"],
                help_text="* (NS, Not Started)\n* (IP, In Progress)\n* (D, Done)",
                max_length=2,
            ),
        ),
    ]
